name: CI

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      BACKEND_IMAGE: pradeep82kumar/backend  
      FRONTEND_IMAGE: pradeep82kumar/frontend 
      DOCKER_CREDENTIALS_ID: ${{ secrets.DOCKER_USERNAME }}  
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Build Backend
        run: |
          cd backend
          pip install -r dependencies.txt

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18' 

      - name: Build Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Build Backend Docker Image
        run: |
          cd backend
          docker build -t $BACKEND_IMAGE .

      - name: Build Frontend Docker Image
        run: |
          cd frontend
          docker build -t $FRONTEND_IMAGE .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Backend Image to Docker Hub
        run: |
          docker push $BACKEND_IMAGE

      - name: Push Frontend Image to Docker Hub
        run: |
          docker push $FRONTEND_IMAGE
